<a href="https://colab.research.google.com/github/Yogapriya-07/Python/blob/main/linear%20regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [29]:
pip install word2number

Requirement already satisfied: word2number in /usr/local/lib/python3.12/dist-packages (1.1)

In [30]:
df = pd.read_csv('/content/employee_salary_dataset.csv')
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [31]:
df.loc[:, 'Experience_Years'] = df['Experience_Years'].fillna('Zero')

In [32]:
df

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [34]:
### Clean 'Experience_Years' column
df['Experience_Years'] = df['Experience_Years'].replace('Zero', 0)
df['Experience_Years'] = pd.to_numeric(df['Experience_Years'])

In [35]:
df

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [37]:
print(df.columns)

Index(['EmployeeID', 'Name', 'Department', 'Experience_Years',
       'Education_Level', 'Age', 'Gender', 'City', 'Monthly_Salary'],
      dtype='object')

In [39]:
# Column 'test_score(out of 10)' does not exist. Removing operation.

In [40]:
# Column 'test_score(out of 10)' does not exist. Removing operation.

In [42]:
df

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [43]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Experience_Years',
       'Education_Level', 'Age', 'Gender', 'City', 'Monthly_Salary'],
      dtype='object')

In [44]:
predictors = ['Experience_Years']
x = df[predictors]
y = df['Monthly_Salary']

In [45]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [46]:
x_train.shape,x_test.shape

((40, 1), (10, 1))

In [51]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [47]:
y_train.shape,y_test.shape

((40,), (10,))

In [48]:
reg = LinearRegression()

In [49]:
model = reg.fit(x_train,y_train)

In [53]:
model.predict([[5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([83054.97555551])

In [54]:
model.score(x_train,y_train)

0.00935844090350868

In [55]:
model.score(x_train,y_train)

0.00935844090350868

In [56]:
model.score(x_train,y_train)

0.00935844090350868